Editando o readme e o contributing
Liebelts/gordura_simulator pull request #19
Opened 2022-10-28 00:54 UTC by AndressaLF

Detalhei a seção de Contribuindo do readme e o arquivo de Contribuiting

2022-10-28 01:38 UTC, AndressaLF commented
Caso você ache minha contribuição interessante poderia colocar a tag do Hacktoberfes, para incentivar mais contribuiçoes. Por favor 😅

2022-10-29 17:46 UTC, Cavernosa requested changes

2022-10-29 17:46 UTC, Cavernosa commented on CONTRIBUTING.md
> +Suas sugestões são muito bem-vindas(os).
"bem-vindas" se refere às sugestões, então não precisa do "(os)" (não existe "os sugestões")

2022-10-29 17:46 UTC, Cavernosa commented on CONTRIBUTING.md
> +5. Mais detalhes [aqui](https://docs.github.com/pt/enterprise-cloud@latest/issues/tracking-your-work-with-issues/creating-an-issue)
Essa frase dá pra reformular tipo assim:
5. Para mais detalhes, veja [Criar um problema](https://docs.github.com/pt/enterprise-cloud@latest/issues/tracking-your-work-with-issues/creating-an-issue) na documentação do Github.

Fica mais descritivo, acessível.

2022-10-29 17:46 UTC, Cavernosa commented on CONTRIBUTING.md
> +4. Mais detalhes [aqui](https://help.github.com/pt/enterprise/2.17/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
Mesma coisa aqui

2022-10-29 18:12 UTC, Cavernosa commented
> Caso você ache minha contribuição interessante poderia colocar a tag do Hacktoberfes, para incentivar mais contribuiçoes. Por favor :sweat_smile:

Precisa da tag pro hacktoberfest contar como válido (os 4 PRs)? Posso colocar.

2022-11-10 01:22 UTC, closed without merging